### ISSUE TITLE
Lock Screen Ui Problem

### ISSUE THREAD

**Issue by EngFadyMondy** [TryHardDood/hermes-mirrors#2]
After install the rom i have a problem with screen locker it's don't need to opening with swap it and never i try every thing and at last i skip it by touch notification and it's open, and i go to  settings to remove lock screen to make it none, when i open option form settings-> Security -> Screen lock -> None , Get Error [Setting has stopped] and can't solve this problem right now.. Plz help i like the rom but that's a big problem with me..

**Comment by TryHardDood** [comment]
Please send more details. Like ROM, version etc. Join the telegram group.

**Comment by EngFadyMondy** [comment]
Mi Redmi note 2, RR 5.8 Rom android 7.1

**Comment by TryHardDood** [comment]
It's a port bug. Nothing to do about it.
